### PR TITLE
Move to Vite

### LINKED ISSUE #1429: Move to Vite

### PR DESCRIPTION
**Pull request by artursapek**
This branch moves Connect off `react-app-rewire` and onto [Vite](https://vitejs.dev/).

Advantages of Vite:
- Very fast dev tooling
- Native ESM support
- Great TypeScript support

This is a dependency for #1343 

I've decided to leave `builder` alone for now and let it stay on `create-react-app`. Took a stab at it and saw some weird stylesheet issues.

## How to test it

Check out this branch `experiment-vite`, then

```
npm i
npm run start -w wormhole-connect
```

Vite should start a local dev server with the Connect demo app.

## Dev experience improvements

Cold boot is about 10x faster faster (`development`: ~40 sec, `experiment-vite`: 3-4 sec)

Most of those gains are from using `swc` and `rollup` (Vite's bundler). Curious to see if others have similarly good results!

### CODE REVIEW

**Comment by artursapek** [comment]
NPM build from `wormhole-connect-loader` works now. multi-chunk `dist` with dynamic imports working!

**Comment by elee1766** [comment]
build time for npm run build for wormhole-connect/wormhole-connect on my computer went from 155 seconds -> 52 seconds. 

:D

**Review by barnjamin — APPROVED** [review]

**Comment by artursapek** [comment]
@elee1766 brings a tear to my eye

**Comment by elee1766** [comment]
> @elee1766 brings a tear to my eye

hopefully the ci pipelines that depend building this will be faster ( I'm working on portal bridge site rn)

as an aside - is there any interest in producing hashed artifacts per branch for this repo? 

the portal bridge ci currently rebuilds the app by doing a clone from the repo within actions. being able to download and verify (with optional manually specified hash for production releases) I think would speed everything up for everyone and also cost less ci minutes.  from a security point of view, I don't think recompiling isn't any better than downloading pre compiled artifacts from github. I think it's actually worse because each build you are re-exposed to the npm registry... 

alternatively I could configure a cache rule in actions for the WHC build in portal, but it seems inefficient, if the assumption is that more sites will integrate like portal, to store duplicate artifacts in the cache of a bunch of different repos instead of just throwing everything as artifacts in the WHC repo.

**Comment by artursapek** [comment]
@elee1766 I'm not sure I understand exactly what you are asking for, but happy to talk about it. merging this change in as-is for now.

**Review by barnjamin — APPROVED** [review]

**Review by M-Picco — APPROVED** [review]

**Review by kev1n-peters — CHANGES_REQUESTED** [review]
Apologies, but we should hold off on merging this

**Review by kev1n-peters — APPROVED** [review]

**Pull request merged**
