### PR TITLE
Update wallet packages

### LINKED ISSUE #1344: [Feature] Add support for Rabby wallet

### LINKED ISSUE #1345: [Feature] Add support for OKX wallet

### LINKED ISSUE #1471: [Feature] Support Metamask Snap for Sui
## What is the expected/desired behavior

- Support connecting to Sui via Metamask Snap
- Requires https://github.com/XLabs/wallet-aggregator-sdk/pull/22, which should be in `0.0.1-alpha.9` of `@xlabs-libs/wallet-aggregator-sui`

### LINKED ISSUE #1472: [Feature] Add support for Solana Wallet Connect
Should be enabled by https://github.com/XLabs/wallet-aggregator-sdk/commit/f54732b02af36c8d67c6fc156554af1469641e95

`0.0.1-alpha.14` of `@xlabs-libs/wallet-aggregator-solana`

### PR DESCRIPTION
**Pull request by M-Picco**
* Update Wallet Aggregator packages to their latest versions
 * Add solana wallets detected through the wallet-standard
 * Use `InjectedWallet` instead of `MetamaskWallet` to detect whatever browser wallet the user has installed

### CODE REVIEW

**Review by kev1n-peters — DISMISSED** [review]

**Comment by kev1n-peters** [comment]
Tested a transfer w/ Rabby wallet and it worked well, nice!

**Comment by kev1n-peters** [comment]
Getting an "invalid QR code" error on Phantom mobile when scanning the QR code provided by the Solana Wallet Connect option.

**Comment by kev1n-peters** [comment]
This also enables Sui Metamask Snap wallet and I successfully competed a transfer with it: https://wormholescan.io/#/tx/21/ccceeb29348f71bdd22ffef43a2a19c1f5b5e17c5cca5411529120182672ade5/61356
This PR also addresses: https://github.com/wormhole-foundation/wormhole-connect/issues/1471

**Review by kev1n-peters — APPROVED** [review]

**Comment by Eiei070922** [comment]
Excuse me. If I want to consult with someone, who can I talk to?

**Pull request merged**
