### PR TITLE
refactor: show connect wallet if network has value

### PR DESCRIPTION
**Pull request by hsnice16**
issue #1343 

https://github.com/wormhole-foundation/wormhole-connect/assets/56081584/889e3ff2-87ef-4b9e-9338-65a345e663f1

### CODE REVIEW

**Comment by artursapek** [comment]
hi, thanks for the PR. this is jumping the gun a little; the changes I described in my issue depend on some other changes I'm working on right now. my Github issue could have been clearer about that.

if you want to narrow the scope of this to simply a UI change that disables the "Connect Wallet" button when no network is selected, I'm happy to consider that change. I don't want to bundle any lazy loading into this PR because it's not actually accomplishing the goal of reducing bundle size, and the code base isn't ready for that to begin with.

**Comment by hsnice16** [comment]
Okay, let me remove the dynamic loading code.

**Comment by hsnice16** [comment]
I have made the changes.

**Comment by artursapek** [comment]
hey thanks. if you squash these into a single commit, I'll cherry pick it to my branch and it will go in with my branch later.

**Comment by hsnice16** [comment]
I have done that.

**Comment by artursapek** [comment]
hi sorry this change was a tiny part of a much bigger change https://github.com/wormhole-foundation/wormhole-connect/pull/1353 and it's not feasible to backport your commit in there now

I'm going to close this, but thank you for the pull request!

**Pull request closed without merging**
