### PR TITLE
Add BSKT to wormhole connect token selection. 

### PR DESCRIPTION
**Pull request by crypt0xg**
BSKT is looking to use wormhole connect for an easy to use interface to travese cross chain. 

PR submitted for details to get added. 

PR also submitted to SDK repo to add details there also.

Please let us know if more submissions are needed.

### CODE REVIEW

**Comment by artursapek** [comment]
hi - we not adding new tokens at this time. however we do hope to provide a way for developers to add arbitrary tokens via a config when deploying Connect on their website. you can track progress on this in https://github.com/wormhole-foundation/wormhole-connect/issues/1287.

**Comment by crypt0xg** [comment]
@artursapek Thanks for the response. A little frustrating to be honest. Is there a particular reason we can't get added? Kind of goes against the whole decentralization aspect and "open source" nature if we're told that token additions are behind a gate like this.

We're trying to make the experience for users, understanding why we're being blocked, when there's no similar requests would be helpful to be able to explain to the community.

**Comment by artursapek** [comment]
@crypt0xg you're welcome to fork the repo and add it to your fork, and deploy that! as you said it's completely open source. we just want to avoid the pull requests end up being an overwhelming firehose of listing requests.

**Comment by crypt0xg** [comment]
@artursapek Appreciate that. With us being the first request and likely to have the most cross-chain connects this week than any other token, I was hoping there would be a little more latitude. Will fork and deploy.

**Comment by aadam-10** [comment]
Hi @crypt0xg, to give a little more context, the process to add tokens in the main repo in this manner isn't sustainable and we simply can't take on the responsibility of handling these requests (which are numerous). The main repo itself must have an owner too, so even automating the acceptance of such requests would still mean that acceptance depends on the maintainers in some way, so it wouldn't be much help on the decentralization front.

We will be mitigating this problem in stages: first to enable integrators to easily configure supported tokens, then to allow Connect to handle arbitrary tokens without configuration, and later to automate collecting metadata about any arbitrary token so that the UI looks appropriate even when dealing with an unknown token. While I don't have exact dates right now, these improvements aren't far off.

**Pull request closed without merging**
