### PR TITLE
Don't round balances

### PR DESCRIPTION
**Pull request by artursapek**
IMG_7494

### CODE REVIEW

**Review by emreboga — DISMISSED** [review]
LGTM!

**Comment by kev1n-peters** [comment]
Do we want to truncate the balance that gets displayed? 
image

**Comment by artursapek** [comment]
> Do we want to truncate the balance that gets displayed? image

good point. I guess this "just worked" before. I'll fix this

**Comment by Wesleyleung** [comment]
Yeah we should truncate the balance that gets displayed too. You should be able to type in as long of a string as you want for your input, but the small gray balance display should also be truncated so that it doesn't bleed over.

**Review by kev1n-peters — APPROVED** [review]

**Comment by Wesleyleung** [comment]
Might have left out truncating the Network Costs too :O 
 
Screenshot 2024-10-22 at 11 44 11 PM

**Pull request merged**
